# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ind <- function(b_mat, n, H) {
    .Call(`_pjnormarcpp_get_ind`, b_mat, n, H)
}

generate_b_cube <- function(ind, k, H, n) {
    .Call(`_pjnormarcpp_generate_b_cube`, ind, k, H, n)
}

get_sigmamat_full <- function(sigmamat_conditional, gamma, k) {
    .Call(`_pjnormarcpp_get_sigmamat_full`, sigmamat_conditional, gamma, k)
}

subtract_y <- function(phi_arr, ind, y, n) {
    .Call(`_pjnormarcpp_subtract_y`, phi_arr, ind, y, n)
}

subtract_b_cube <- function(b_cube, phi_arr, ind, n) {
    .Call(`_pjnormarcpp_subtract_b_cube`, b_cube, phi_arr, ind, n)
}

generatemu_posterior <- function(mu_prior_precision, precision_full_arr, ind, mu_prior_mu, subtracted_b_cube, subtracted_y, n) {
    .Call(`_pjnormarcpp_generatemu_posterior`, mu_prior_precision, precision_full_arr, ind, mu_prior_mu, subtracted_b_cube, subtracted_y, n)
}

center_y <- function(subtracted_y, subtracted_b_cube, mu, n) {
    .Call(`_pjnormarcpp_center_y`, subtracted_y, subtracted_b_cube, mu, n)
}

generategamma_posterior <- function(ind, sigmamat_conditional_arr, gamma_prior_precision, gamma_prior_mu, centered_y, h, k) {
    .Call(`_pjnormarcpp_generategamma_posterior`, ind, sigmamat_conditional_arr, gamma_prior_precision, gamma_prior_mu, centered_y, h, k)
}

diff_centered_y <- function(centered_y, gamma_mat, ind, k, n) {
    .Call(`_pjnormarcpp_diff_centered_y`, centered_y, gamma_mat, ind, k, n)
}

get_w <- function(y, mu, ind, H, k, n) {
    .Call(`_pjnormarcpp_get_w`, y, mu, ind, H, k, n)
}

generatephi_posterior <- function(ind1, w, precision_full_arr, phi_arr, phi_prior_precision, phi_prior_mu, k, h, kk) {
    .Call(`_pjnormarcpp_generatephi_posterior`, ind1, w, precision_full_arr, phi_arr, phi_prior_precision, phi_prior_mu, k, h, kk)
}

gen_r <- function(ind, mu_present_mat, precision_full_arr, phi_arr, sphericaldata, augmenteddata_raw, nn, n, r, k) {
    .Call(`_pjnormarcpp_gen_r`, ind, mu_present_mat, precision_full_arr, phi_arr, sphericaldata, augmenteddata_raw, nn, n, r, k)
}

gen_r_group <- function(ind, ind1, mu_present_mat, precision_full_arr, phi_arr, sphericaldata, augmenteddata_raw, nn, n, r, k) {
    .Call(`_pjnormarcpp_gen_r_group`, ind, ind1, mu_present_mat, precision_full_arr, phi_arr, sphericaldata, augmenteddata_raw, nn, n, r, k)
}

mcmc_chain_pjnormar1 <- function(sphericaldata, b_mat, iterations = 5000L) {
    .Call(`_pjnormarcpp_mcmc_chain_pjnormar1`, sphericaldata, b_mat, iterations)
}

mcmc_chain_pjnormar1_group <- function(sphericaldata, protein_first, b_mat, iterations = 5000L) {
    .Call(`_pjnormarcpp_mcmc_chain_pjnormar1_group`, sphericaldata, protein_first, b_mat, iterations)
}

mvrnormArma <- function(k, mu, sigma) {
    .Call(`_pjnormarcpp_mvrnormArma`, k, mu, sigma)
}

wishartArma <- function(k, n, sigma) {
    .Call(`_pjnormarcpp_wishartArma`, k, n, sigma)
}

